# Use an official Python runtime as a parent image
FROM python:3-alpine

RUN apk add ncurses

COPY . /app

WORKDIR /app

RUN pip install -r requirements.txt

# Run command when the container launches
CMD ["asciinema", "rec"]
